events {}

http {
    upstream user_service {
        server user-service:8001;
    }

    upstream agent_service {
        server agent-service:8002;
    }

    server {
        listen 80;

        location /api/users/ {
            proxy_pass http://user_service/;
        }

        location /api/agents/ {
            proxy_pass http://agent_service/;
        }
    }
}
